// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: editorapi.proto

package editorapi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SmartsheetResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FileID  string `protobuf:"bytes,2,opt,name=fileID,proto3" json:"fileID,omitempty"`
	SheetID string `protobuf:"bytes,3,opt,name=sheetID,proto3" json:"sheetID,omitempty"`
	// Types that are assignable to Request:
	//	*SmartsheetResourceRequest_GetViews
	//	*SmartsheetResourceRequest_GetRecords
	//	*SmartsheetResourceRequest_GetFields
	//	*SmartsheetResourceRequest_AddView
	//	*SmartsheetResourceRequest_DeleteViews
	//	*SmartsheetResourceRequest_AddRecords
	//	*SmartsheetResourceRequest_UpdateRecords
	//	*SmartsheetResourceRequest_DeleteRecords
	//	*SmartsheetResourceRequest_AddFields
	//	*SmartsheetResourceRequest_UpdateFields
	//	*SmartsheetResourceRequest_DeleteFields
	Request isSmartsheetResourceRequest_Request `protobuf_oneof:"request"`
}

func (x *SmartsheetResourceRequest) Reset() {
	*x = SmartsheetResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartsheetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartsheetResourceRequest) ProtoMessage() {}

func (x *SmartsheetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartsheetResourceRequest.ProtoReflect.Descriptor instead.
func (*SmartsheetResourceRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{0}
}

func (x *SmartsheetResourceRequest) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SmartsheetResourceRequest) GetFileID() string {
	if x != nil {
		return x.FileID
	}
	return ""
}

func (x *SmartsheetResourceRequest) GetSheetID() string {
	if x != nil {
		return x.SheetID
	}
	return ""
}

func (m *SmartsheetResourceRequest) GetRequest() isSmartsheetResourceRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetGetViews() *GetViewsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_GetViews); ok {
		return x.GetViews
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetGetRecords() *GetRecordsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_GetRecords); ok {
		return x.GetRecords
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetGetFields() *GetFieldsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_GetFields); ok {
		return x.GetFields
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetAddView() *AddViewRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_AddView); ok {
		return x.AddView
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetDeleteViews() *DeleteViewsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_DeleteViews); ok {
		return x.DeleteViews
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetAddRecords() *AddRecordsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_AddRecords); ok {
		return x.AddRecords
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetUpdateRecords() *UpdateRecordsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_UpdateRecords); ok {
		return x.UpdateRecords
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetDeleteRecords() *DeleteRecordsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_DeleteRecords); ok {
		return x.DeleteRecords
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetAddFields() *AddFieldsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_AddFields); ok {
		return x.AddFields
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetUpdateFields() *UpdateFieldsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_UpdateFields); ok {
		return x.UpdateFields
	}
	return nil
}

func (x *SmartsheetResourceRequest) GetDeleteFields() *DeleteFieldsRequest {
	if x, ok := x.GetRequest().(*SmartsheetResourceRequest_DeleteFields); ok {
		return x.DeleteFields
	}
	return nil
}

type isSmartsheetResourceRequest_Request interface {
	isSmartsheetResourceRequest_Request()
}

type SmartsheetResourceRequest_GetViews struct {
	GetViews *GetViewsRequest `protobuf:"bytes,4,opt,name=getViews,proto3,oneof"`
}

type SmartsheetResourceRequest_GetRecords struct {
	GetRecords *GetRecordsRequest `protobuf:"bytes,5,opt,name=getRecords,proto3,oneof"`
}

type SmartsheetResourceRequest_GetFields struct {
	GetFields *GetFieldsRequest `protobuf:"bytes,6,opt,name=getFields,proto3,oneof"`
}

type SmartsheetResourceRequest_AddView struct {
	AddView *AddViewRequest `protobuf:"bytes,7,opt,name=addView,proto3,oneof"`
}

type SmartsheetResourceRequest_DeleteViews struct {
	DeleteViews *DeleteViewsRequest `protobuf:"bytes,8,opt,name=deleteViews,proto3,oneof"`
}

type SmartsheetResourceRequest_AddRecords struct {
	AddRecords *AddRecordsRequest `protobuf:"bytes,9,opt,name=addRecords,proto3,oneof"`
}

type SmartsheetResourceRequest_UpdateRecords struct {
	UpdateRecords *UpdateRecordsRequest `protobuf:"bytes,10,opt,name=updateRecords,proto3,oneof"`
}

type SmartsheetResourceRequest_DeleteRecords struct {
	DeleteRecords *DeleteRecordsRequest `protobuf:"bytes,11,opt,name=deleteRecords,proto3,oneof"`
}

type SmartsheetResourceRequest_AddFields struct {
	AddFields *AddFieldsRequest `protobuf:"bytes,12,opt,name=addFields,proto3,oneof"`
}

type SmartsheetResourceRequest_UpdateFields struct {
	UpdateFields *UpdateFieldsRequest `protobuf:"bytes,13,opt,name=updateFields,proto3,oneof"`
}

type SmartsheetResourceRequest_DeleteFields struct {
	DeleteFields *DeleteFieldsRequest `protobuf:"bytes,14,opt,name=deleteFields,proto3,oneof"`
}

func (*SmartsheetResourceRequest_GetViews) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_GetRecords) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_GetFields) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_AddView) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_DeleteViews) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_AddRecords) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_UpdateRecords) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_DeleteRecords) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_AddFields) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_UpdateFields) isSmartsheetResourceRequest_Request() {}

func (*SmartsheetResourceRequest_DeleteFields) isSmartsheetResourceRequest_Request() {}

type SmartsheetResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	GetViews      *GetViewsResponse      `protobuf:"bytes,2,opt,name=getViews,proto3" json:"getViews,omitempty"`
	GetRecords    *GetRecordsResponse    `protobuf:"bytes,3,opt,name=getRecords,proto3" json:"getRecords,omitempty"`
	GetFields     *GetFieldsResponse     `protobuf:"bytes,4,opt,name=getFields,proto3" json:"getFields,omitempty"`
	AddView       *AddViewResponse       `protobuf:"bytes,5,opt,name=addView,proto3" json:"addView,omitempty"`
	DeleteViews   *DeleteViewsResponse   `protobuf:"bytes,6,opt,name=deleteViews,proto3" json:"deleteViews,omitempty"`
	AddRecords    *AddRecordsResponse    `protobuf:"bytes,7,opt,name=addRecords,proto3" json:"addRecords,omitempty"`
	UpdateRecords *UpdateRecordsResponse `protobuf:"bytes,8,opt,name=updateRecords,proto3" json:"updateRecords,omitempty"`
	DeleteRecords *DeleteRecordsResponse `protobuf:"bytes,9,opt,name=deleteRecords,proto3" json:"deleteRecords,omitempty"`
	AddFields     *AddFieldsResponse     `protobuf:"bytes,10,opt,name=addFields,proto3" json:"addFields,omitempty"`
	UpdateFields  *UpdateFieldsResponse  `protobuf:"bytes,11,opt,name=updateFields,proto3" json:"updateFields,omitempty"`
	DeleteFields  *DeleteFieldsResponse  `protobuf:"bytes,12,opt,name=deleteFields,proto3" json:"deleteFields,omitempty"`
}

func (x *SmartsheetResourceResponse) Reset() {
	*x = SmartsheetResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartsheetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartsheetResourceResponse) ProtoMessage() {}

func (x *SmartsheetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartsheetResourceResponse.ProtoReflect.Descriptor instead.
func (*SmartsheetResourceResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{1}
}

func (x *SmartsheetResourceResponse) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SmartsheetResourceResponse) GetGetViews() *GetViewsResponse {
	if x != nil {
		return x.GetViews
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetGetRecords() *GetRecordsResponse {
	if x != nil {
		return x.GetRecords
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetGetFields() *GetFieldsResponse {
	if x != nil {
		return x.GetFields
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetAddView() *AddViewResponse {
	if x != nil {
		return x.AddView
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetDeleteViews() *DeleteViewsResponse {
	if x != nil {
		return x.DeleteViews
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetAddRecords() *AddRecordsResponse {
	if x != nil {
		return x.AddRecords
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetUpdateRecords() *UpdateRecordsResponse {
	if x != nil {
		return x.UpdateRecords
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetDeleteRecords() *DeleteRecordsResponse {
	if x != nil {
		return x.DeleteRecords
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetAddFields() *AddFieldsResponse {
	if x != nil {
		return x.AddFields
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetUpdateFields() *UpdateFieldsResponse {
	if x != nil {
		return x.UpdateFields
	}
	return nil
}

func (x *SmartsheetResourceResponse) GetDeleteFields() *DeleteFieldsResponse {
	if x != nil {
		return x.DeleteFields
	}
	return nil
}

type View struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewID   string `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	ViewName string `protobuf:"bytes,2,opt,name=viewName,proto3" json:"viewName,omitempty"`
	ViewType string `protobuf:"bytes,3,opt,name=viewType,proto3" json:"viewType,omitempty"`
}

func (x *View) Reset() {
	*x = View{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{2}
}

func (x *View) GetViewID() string {
	if x != nil {
		return x.ViewID
	}
	return ""
}

func (x *View) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *View) GetViewType() string {
	if x != nil {
		return x.ViewType
	}
	return ""
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordID   string            `protobuf:"bytes,1,opt,name=recordID,proto3" json:"recordID,omitempty"`
	CreateTime int64             `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime int64             `protobuf:"varint,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Values     map[string]string `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // key 为 fieldName
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{3}
}

func (x *Record) GetRecordID() string {
	if x != nil {
		return x.RecordID
	}
	return ""
}

func (x *Record) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Record) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Record) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AddRecordsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AddRecordsReq) Reset() {
	*x = AddRecordsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordsReq) ProtoMessage() {}

func (x *AddRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordsReq.ProtoReflect.Descriptor instead.
func (*AddRecordsReq) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{4}
}

func (x *AddRecordsReq) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdateRecordsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordID string            `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	Values   map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateRecordsReq) Reset() {
	*x = UpdateRecordsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordsReq) ProtoMessage() {}

func (x *UpdateRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordsReq.ProtoReflect.Descriptor instead.
func (*UpdateRecordsReq) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRecordsReq) GetRecordID() string {
	if x != nil {
		return x.RecordID
	}
	return ""
}

func (x *UpdateRecordsReq) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldID   string `protobuf:"bytes,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	FieldName string `protobuf:"bytes,2,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	FieldType string `protobuf:"bytes,3,opt,name=fieldType,proto3" json:"fieldType,omitempty"`
	Property  string `protobuf:"bytes,4,opt,name=property,proto3" json:"property,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{6}
}

func (x *Field) GetFieldID() string {
	if x != nil {
		return x.FieldID
	}
	return ""
}

func (x *Field) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *Field) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *Field) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type AddFieldsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName string `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	FieldType string `protobuf:"bytes,2,opt,name=fieldType,proto3" json:"fieldType,omitempty"`
	Property  string `protobuf:"bytes,3,opt,name=property,proto3" json:"property,omitempty"`
}

func (x *AddFieldsReq) Reset() {
	*x = AddFieldsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFieldsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFieldsReq) ProtoMessage() {}

func (x *AddFieldsReq) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFieldsReq.ProtoReflect.Descriptor instead.
func (*AddFieldsReq) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{7}
}

func (x *AddFieldsReq) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *AddFieldsReq) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *AddFieldsReq) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName string `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	Desc      bool   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *Sort) Reset() {
	*x = Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{8}
}

func (x *Sort) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *Sort) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// 获取所有视图请求
type GetViewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewIDs []string `protobuf:"bytes,1,rep,name=viewIDs,proto3" json:"viewIDs,omitempty"`
	Offset  uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量，初始值为 0
	Limit   uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // 分页大小, 每页返回多少条数据
}

func (x *GetViewsRequest) Reset() {
	*x = GetViewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewsRequest) ProtoMessage() {}

func (x *GetViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewsRequest.ProtoReflect.Descriptor instead.
func (*GetViewsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{9}
}

func (x *GetViewsRequest) GetViewIDs() []string {
	if x != nil {
		return x.ViewIDs
	}
	return nil
}

func (x *GetViewsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetViewsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取指定表格指定子表中的所有视图回包
type GetViewsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   uint32  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`     // 符合筛选条件的总记录条数
	HasMore bool    `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"` // 是否还有更多项
	Next    uint32  `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`       // 下次下一个搜索结果的偏移量
	Views   []*View `protobuf:"bytes,4,rep,name=views,proto3" json:"views,omitempty"`
}

func (x *GetViewsResponse) Reset() {
	*x = GetViewsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewsResponse) ProtoMessage() {}

func (x *GetViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewsResponse.ProtoReflect.Descriptor instead.
func (*GetViewsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{10}
}

func (x *GetViewsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetViewsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetViewsResponse) GetNext() uint32 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *GetViewsResponse) GetViews() []*View {
	if x != nil {
		return x.Views
	}
	return nil
}

// 新建视图请求，创建一个视图
type AddViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewName string `protobuf:"bytes,1,opt,name=viewName,proto3" json:"viewName,omitempty"`
	ViewType string `protobuf:"bytes,2,opt,name=viewType,proto3" json:"viewType,omitempty"`
}

func (x *AddViewRequest) Reset() {
	*x = AddViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddViewRequest) ProtoMessage() {}

func (x *AddViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddViewRequest.ProtoReflect.Descriptor instead.
func (*AddViewRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{11}
}

func (x *AddViewRequest) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *AddViewRequest) GetViewType() string {
	if x != nil {
		return x.ViewType
	}
	return ""
}

// 新建视图回包
type AddViewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View *View `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
}

func (x *AddViewResponse) Reset() {
	*x = AddViewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddViewResponse) ProtoMessage() {}

func (x *AddViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddViewResponse.ProtoReflect.Descriptor instead.
func (*AddViewResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{12}
}

func (x *AddViewResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

// 删除指定表格指定子表中的指定视图请求
type DeleteViewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewIDs []string `protobuf:"bytes,1,rep,name=viewIDs,proto3" json:"viewIDs,omitempty"`
}

func (x *DeleteViewsRequest) Reset() {
	*x = DeleteViewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteViewsRequest) ProtoMessage() {}

func (x *DeleteViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteViewsRequest.ProtoReflect.Descriptor instead.
func (*DeleteViewsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteViewsRequest) GetViewIDs() []string {
	if x != nil {
		return x.ViewIDs
	}
	return nil
}

// 删除指定表格指定子表中的指定视图回包
type DeleteViewsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteViewsResponse) Reset() {
	*x = DeleteViewsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteViewsResponse) ProtoMessage() {}

func (x *DeleteViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteViewsResponse.ProtoReflect.Descriptor instead.
func (*DeleteViewsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{14}
}

// 获取指定表格和子表下指定视图中的所有记录、指定返回记录里要包含的字段、获取指定筛选条件和指定数量的记录三个接口合一
type GetRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewID     string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	RecordIDs  []string `protobuf:"bytes,2,rep,name=recordIDs,proto3" json:"recordIDs,omitempty"`
	FieldNames []string `protobuf:"bytes,3,rep,name=fieldNames,proto3" json:"fieldNames,omitempty"`
	Sort       []*Sort  `protobuf:"bytes,4,rep,name=sort,proto3" json:"sort,omitempty"`
	Offset     uint32   `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit      uint32   `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetRecordsRequest) Reset() {
	*x = GetRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsRequest) ProtoMessage() {}

func (x *GetRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{15}
}

func (x *GetRecordsRequest) GetViewID() string {
	if x != nil {
		return x.ViewID
	}
	return ""
}

func (x *GetRecordsRequest) GetRecordIDs() []string {
	if x != nil {
		return x.RecordIDs
	}
	return nil
}

func (x *GetRecordsRequest) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

func (x *GetRecordsRequest) GetSort() []*Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *GetRecordsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRecordsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取指定表格和子表下指定视图中的所有记录回包
type GetRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   uint32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	HasMore bool      `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	Next    uint32    `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`
	Records []*Record `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *GetRecordsResponse) Reset() {
	*x = GetRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsResponse) ProtoMessage() {}

func (x *GetRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetRecordsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{16}
}

func (x *GetRecordsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRecordsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetRecordsResponse) GetNext() uint32 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *GetRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// 在指定表格和子表中创建一到多条新记录请求
type AddRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*AddRecordsReq `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *AddRecordsRequest) Reset() {
	*x = AddRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordsRequest) ProtoMessage() {}

func (x *AddRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordsRequest.ProtoReflect.Descriptor instead.
func (*AddRecordsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{17}
}

func (x *AddRecordsRequest) GetRecords() []*AddRecordsReq {
	if x != nil {
		return x.Records
	}
	return nil
}

// 在指定表格和子表中创建一到多条新记录回包
type AddRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *AddRecordsResponse) Reset() {
	*x = AddRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordsResponse) ProtoMessage() {}

func (x *AddRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordsResponse.ProtoReflect.Descriptor instead.
func (*AddRecordsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{18}
}

func (x *AddRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// 更新指定表格和子表中的一到多条记录请求
type UpdateRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*UpdateRecordsReq `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *UpdateRecordsRequest) Reset() {
	*x = UpdateRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordsRequest) ProtoMessage() {}

func (x *UpdateRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordsRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateRecordsRequest) GetRecords() []*UpdateRecordsReq {
	if x != nil {
		return x.Records
	}
	return nil
}

// 更新指定表格和子表中的一到多条记录回包
type UpdateRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *UpdateRecordsResponse) Reset() {
	*x = UpdateRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordsResponse) ProtoMessage() {}

func (x *UpdateRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordsResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// 删除指定表格和子表中的一到多条记录请求
type DeleteRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordIDs []string `protobuf:"bytes,1,rep,name=recordIDs,proto3" json:"recordIDs,omitempty"`
}

func (x *DeleteRecordsRequest) Reset() {
	*x = DeleteRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordsRequest) ProtoMessage() {}

func (x *DeleteRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordsRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRecordsRequest) GetRecordIDs() []string {
	if x != nil {
		return x.RecordIDs
	}
	return nil
}

// 删除指定表格和子表中的一到多条记录回包
type DeleteRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRecordsResponse) Reset() {
	*x = DeleteRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordsResponse) ProtoMessage() {}

func (x *DeleteRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordsResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{22}
}

// 获取指定表格和子表中的所有字段请求
type GetFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewID string `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetFieldsRequest) Reset() {
	*x = GetFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsRequest) ProtoMessage() {}

func (x *GetFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetFieldsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{23}
}

func (x *GetFieldsRequest) GetViewID() string {
	if x != nil {
		return x.ViewID
	}
	return ""
}

func (x *GetFieldsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetFieldsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取指定表格和子表中的所有字段回包
type GetFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	HasMore bool     `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	Next    uint32   `protobuf:"varint,3,opt,name=next,proto3" json:"next,omitempty"`
	Fields  []*Field `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetFieldsResponse) Reset() {
	*x = GetFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsResponse) ProtoMessage() {}

func (x *GetFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetFieldsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{24}
}

func (x *GetFieldsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFieldsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetFieldsResponse) GetNext() uint32 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *GetFieldsResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 新增字段请求
type AddFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*AddFieldsReq `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *AddFieldsRequest) Reset() {
	*x = AddFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFieldsRequest) ProtoMessage() {}

func (x *AddFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFieldsRequest.ProtoReflect.Descriptor instead.
func (*AddFieldsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{25}
}

func (x *AddFieldsRequest) GetFields() []*AddFieldsReq {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 新增字段回包
type AddFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *AddFieldsResponse) Reset() {
	*x = AddFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFieldsResponse) ProtoMessage() {}

func (x *AddFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFieldsResponse.ProtoReflect.Descriptor instead.
func (*AddFieldsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{26}
}

func (x *AddFieldsResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 更新字段请求
type UpdateFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *UpdateFieldsRequest) Reset() {
	*x = UpdateFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFieldsRequest) ProtoMessage() {}

func (x *UpdateFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFieldsRequest.ProtoReflect.Descriptor instead.
func (*UpdateFieldsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateFieldsRequest) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 更新字段回包
type UpdateFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *UpdateFieldsResponse) Reset() {
	*x = UpdateFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFieldsResponse) ProtoMessage() {}

func (x *UpdateFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFieldsResponse.ProtoReflect.Descriptor instead.
func (*UpdateFieldsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateFieldsResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 删除字段请求
type DeleteFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldIDs []string `protobuf:"bytes,1,rep,name=fieldIDs,proto3" json:"fieldIDs,omitempty"`
}

func (x *DeleteFieldsRequest) Reset() {
	*x = DeleteFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFieldsRequest) ProtoMessage() {}

func (x *DeleteFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFieldsRequest.ProtoReflect.Descriptor instead.
func (*DeleteFieldsRequest) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteFieldsRequest) GetFieldIDs() []string {
	if x != nil {
		return x.FieldIDs
	}
	return nil
}

// 删除字段回包
type DeleteFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFieldsResponse) Reset() {
	*x = DeleteFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_editorapi_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFieldsResponse) ProtoMessage() {}

func (x *DeleteFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editorapi_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFieldsResponse.ProtoReflect.Descriptor instead.
func (*DeleteFieldsResponse) Descriptor() ([]byte, []int) {
	return file_editorapi_proto_rawDescGZIP(), []int{30}
}

var File_editorapi_proto protoreflect.FileDescriptor

var file_editorapi_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x22, 0xbc, 0x06, 0x0a,
	0x19, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x73, 0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68,
	0x65, 0x65, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68, 0x65,
	0x65, 0x74, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x3e,
	0x0a, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x3b,
	0x0a, 0x09, 0x67, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x09, 0x67, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x56, 0x69, 0x65, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x69, 0x65, 0x77,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x56, 0x69,
	0x65, 0x77, 0x12, 0x41, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x3e, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x47, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x47,
	0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x3b, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x61, 0x64, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x44, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x44, 0x0a, 0x0c, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xf5, 0x05, 0x0a, 0x1a,
	0x53, 0x6d, 0x61, 0x72, 0x74, 0x73, 0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x37, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x67, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x3d, 0x0a, 0x0a, 0x67,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x67, 0x65,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x67, 0x65, 0x74,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x56, 0x69, 0x65,
	0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x07, 0x61, 0x64, 0x64, 0x56, 0x69, 0x65, 0x77, 0x12, 0x40, 0x0a, 0x0b,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x3d,
	0x0a, 0x0a, 0x61, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x46, 0x0a,
	0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x46, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x3a, 0x0a,
	0x09, 0x61, 0x64, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09,
	0x61, 0x64, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x43, 0x0a, 0x0c, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x43,
	0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x22, 0x56, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x69, 0x65, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x69, 0x65,
	0x77, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x76, 0x69, 0x65, 0x77, 0x54, 0x79, 0x70, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x3c, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xaa, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44,
	0x12, 0x3f, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x79, 0x0a, 0x05,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x22, 0x66, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x22,
	0x38, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x59, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x56, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x69, 0x65, 0x77, 0x49, 0x44, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x7d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x25, 0x0a, 0x05,
	0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x05, 0x76, 0x69,
	0x65, 0x77, 0x73, 0x22, 0x48, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x65, 0x77, 0x54, 0x79, 0x70, 0x65, 0x22, 0x36, 0x0a,
	0x0f, 0x41, 0x64, 0x64, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x52,
	0x04, 0x76, 0x69, 0x65, 0x77, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x69, 0x65, 0x77, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69,
	0x65, 0x77, 0x49, 0x44, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbc, 0x01, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4d,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f,
	0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x41, 0x0a, 0x12,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22,
	0x4d, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x44,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x22, 0x34, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x58, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x69, 0x65, 0x77, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x69, 0x65, 0x77, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x81, 0x01,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73,
	0x4d, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d,
	0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x22, 0x43, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x3d, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x3f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x40, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x31, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x44, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_editorapi_proto_rawDescOnce sync.Once
	file_editorapi_proto_rawDescData = file_editorapi_proto_rawDesc
)

func file_editorapi_proto_rawDescGZIP() []byte {
	file_editorapi_proto_rawDescOnce.Do(func() {
		file_editorapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_editorapi_proto_rawDescData)
	})
	return file_editorapi_proto_rawDescData
}

var file_editorapi_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_editorapi_proto_goTypes = []interface{}{
	(*SmartsheetResourceRequest)(nil),  // 0: editorapi.SmartsheetResourceRequest
	(*SmartsheetResourceResponse)(nil), // 1: editorapi.SmartsheetResourceResponse
	(*View)(nil),                       // 2: editorapi.View
	(*Record)(nil),                     // 3: editorapi.Record
	(*AddRecordsReq)(nil),              // 4: editorapi.AddRecordsReq
	(*UpdateRecordsReq)(nil),           // 5: editorapi.UpdateRecordsReq
	(*Field)(nil),                      // 6: editorapi.Field
	(*AddFieldsReq)(nil),               // 7: editorapi.AddFieldsReq
	(*Sort)(nil),                       // 8: editorapi.Sort
	(*GetViewsRequest)(nil),            // 9: editorapi.GetViewsRequest
	(*GetViewsResponse)(nil),           // 10: editorapi.GetViewsResponse
	(*AddViewRequest)(nil),             // 11: editorapi.AddViewRequest
	(*AddViewResponse)(nil),            // 12: editorapi.AddViewResponse
	(*DeleteViewsRequest)(nil),         // 13: editorapi.DeleteViewsRequest
	(*DeleteViewsResponse)(nil),        // 14: editorapi.DeleteViewsResponse
	(*GetRecordsRequest)(nil),          // 15: editorapi.GetRecordsRequest
	(*GetRecordsResponse)(nil),         // 16: editorapi.GetRecordsResponse
	(*AddRecordsRequest)(nil),          // 17: editorapi.AddRecordsRequest
	(*AddRecordsResponse)(nil),         // 18: editorapi.AddRecordsResponse
	(*UpdateRecordsRequest)(nil),       // 19: editorapi.UpdateRecordsRequest
	(*UpdateRecordsResponse)(nil),      // 20: editorapi.UpdateRecordsResponse
	(*DeleteRecordsRequest)(nil),       // 21: editorapi.DeleteRecordsRequest
	(*DeleteRecordsResponse)(nil),      // 22: editorapi.DeleteRecordsResponse
	(*GetFieldsRequest)(nil),           // 23: editorapi.GetFieldsRequest
	(*GetFieldsResponse)(nil),          // 24: editorapi.GetFieldsResponse
	(*AddFieldsRequest)(nil),           // 25: editorapi.AddFieldsRequest
	(*AddFieldsResponse)(nil),          // 26: editorapi.AddFieldsResponse
	(*UpdateFieldsRequest)(nil),        // 27: editorapi.UpdateFieldsRequest
	(*UpdateFieldsResponse)(nil),       // 28: editorapi.UpdateFieldsResponse
	(*DeleteFieldsRequest)(nil),        // 29: editorapi.DeleteFieldsRequest
	(*DeleteFieldsResponse)(nil),       // 30: editorapi.DeleteFieldsResponse
	nil,                                // 31: editorapi.Record.ValuesEntry
	nil,                                // 32: editorapi.AddRecordsReq.ValuesEntry
	nil,                                // 33: editorapi.UpdateRecordsReq.ValuesEntry
}
var file_editorapi_proto_depIdxs = []int32{
	9,  // 0: editorapi.SmartsheetResourceRequest.getViews:type_name -> editorapi.GetViewsRequest
	15, // 1: editorapi.SmartsheetResourceRequest.getRecords:type_name -> editorapi.GetRecordsRequest
	23, // 2: editorapi.SmartsheetResourceRequest.getFields:type_name -> editorapi.GetFieldsRequest
	11, // 3: editorapi.SmartsheetResourceRequest.addView:type_name -> editorapi.AddViewRequest
	13, // 4: editorapi.SmartsheetResourceRequest.deleteViews:type_name -> editorapi.DeleteViewsRequest
	17, // 5: editorapi.SmartsheetResourceRequest.addRecords:type_name -> editorapi.AddRecordsRequest
	19, // 6: editorapi.SmartsheetResourceRequest.updateRecords:type_name -> editorapi.UpdateRecordsRequest
	21, // 7: editorapi.SmartsheetResourceRequest.deleteRecords:type_name -> editorapi.DeleteRecordsRequest
	25, // 8: editorapi.SmartsheetResourceRequest.addFields:type_name -> editorapi.AddFieldsRequest
	27, // 9: editorapi.SmartsheetResourceRequest.updateFields:type_name -> editorapi.UpdateFieldsRequest
	29, // 10: editorapi.SmartsheetResourceRequest.deleteFields:type_name -> editorapi.DeleteFieldsRequest
	10, // 11: editorapi.SmartsheetResourceResponse.getViews:type_name -> editorapi.GetViewsResponse
	16, // 12: editorapi.SmartsheetResourceResponse.getRecords:type_name -> editorapi.GetRecordsResponse
	24, // 13: editorapi.SmartsheetResourceResponse.getFields:type_name -> editorapi.GetFieldsResponse
	12, // 14: editorapi.SmartsheetResourceResponse.addView:type_name -> editorapi.AddViewResponse
	14, // 15: editorapi.SmartsheetResourceResponse.deleteViews:type_name -> editorapi.DeleteViewsResponse
	18, // 16: editorapi.SmartsheetResourceResponse.addRecords:type_name -> editorapi.AddRecordsResponse
	20, // 17: editorapi.SmartsheetResourceResponse.updateRecords:type_name -> editorapi.UpdateRecordsResponse
	22, // 18: editorapi.SmartsheetResourceResponse.deleteRecords:type_name -> editorapi.DeleteRecordsResponse
	26, // 19: editorapi.SmartsheetResourceResponse.addFields:type_name -> editorapi.AddFieldsResponse
	28, // 20: editorapi.SmartsheetResourceResponse.updateFields:type_name -> editorapi.UpdateFieldsResponse
	30, // 21: editorapi.SmartsheetResourceResponse.deleteFields:type_name -> editorapi.DeleteFieldsResponse
	31, // 22: editorapi.Record.values:type_name -> editorapi.Record.ValuesEntry
	32, // 23: editorapi.AddRecordsReq.values:type_name -> editorapi.AddRecordsReq.ValuesEntry
	33, // 24: editorapi.UpdateRecordsReq.values:type_name -> editorapi.UpdateRecordsReq.ValuesEntry
	2,  // 25: editorapi.GetViewsResponse.views:type_name -> editorapi.View
	2,  // 26: editorapi.AddViewResponse.view:type_name -> editorapi.View
	8,  // 27: editorapi.GetRecordsRequest.sort:type_name -> editorapi.Sort
	3,  // 28: editorapi.GetRecordsResponse.records:type_name -> editorapi.Record
	4,  // 29: editorapi.AddRecordsRequest.records:type_name -> editorapi.AddRecordsReq
	3,  // 30: editorapi.AddRecordsResponse.records:type_name -> editorapi.Record
	5,  // 31: editorapi.UpdateRecordsRequest.records:type_name -> editorapi.UpdateRecordsReq
	3,  // 32: editorapi.UpdateRecordsResponse.records:type_name -> editorapi.Record
	6,  // 33: editorapi.GetFieldsResponse.fields:type_name -> editorapi.Field
	7,  // 34: editorapi.AddFieldsRequest.fields:type_name -> editorapi.AddFieldsReq
	6,  // 35: editorapi.AddFieldsResponse.fields:type_name -> editorapi.Field
	6,  // 36: editorapi.UpdateFieldsRequest.fields:type_name -> editorapi.Field
	6,  // 37: editorapi.UpdateFieldsResponse.fields:type_name -> editorapi.Field
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_editorapi_proto_init() }
func file_editorapi_proto_init() {
	if File_editorapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_editorapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartsheetResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartsheetResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*View); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecordsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecordsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFieldsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddViewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteViewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteViewsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_editorapi_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_editorapi_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SmartsheetResourceRequest_GetViews)(nil),
		(*SmartsheetResourceRequest_GetRecords)(nil),
		(*SmartsheetResourceRequest_GetFields)(nil),
		(*SmartsheetResourceRequest_AddView)(nil),
		(*SmartsheetResourceRequest_DeleteViews)(nil),
		(*SmartsheetResourceRequest_AddRecords)(nil),
		(*SmartsheetResourceRequest_UpdateRecords)(nil),
		(*SmartsheetResourceRequest_DeleteRecords)(nil),
		(*SmartsheetResourceRequest_AddFields)(nil),
		(*SmartsheetResourceRequest_UpdateFields)(nil),
		(*SmartsheetResourceRequest_DeleteFields)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_editorapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_editorapi_proto_goTypes,
		DependencyIndexes: file_editorapi_proto_depIdxs,
		MessageInfos:      file_editorapi_proto_msgTypes,
	}.Build()
	File_editorapi_proto = out.File
	file_editorapi_proto_rawDesc = nil
	file_editorapi_proto_goTypes = nil
	file_editorapi_proto_depIdxs = nil
}
