// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: oneof.proto

package oneof

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StatusTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jk string `protobuf:"bytes,1,opt,name=jk,proto3" json:"jk,omitempty"`
	// Types that are assignable to Show:
	//	*StatusTest_Test
	//	*StatusTest_Hh
	Show isStatusTest_Show `protobuf_oneof:"show"`
}

func (x *StatusTest) Reset() {
	*x = StatusTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusTest) ProtoMessage() {}

func (x *StatusTest) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusTest.ProtoReflect.Descriptor instead.
func (*StatusTest) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *StatusTest) GetJk() string {
	if x != nil {
		return x.Jk
	}
	return ""
}

func (m *StatusTest) GetShow() isStatusTest_Show {
	if m != nil {
		return m.Show
	}
	return nil
}

func (x *StatusTest) GetTest() string {
	if x, ok := x.GetShow().(*StatusTest_Test); ok {
		return x.Test
	}
	return ""
}

func (x *StatusTest) GetHh() int32 {
	if x, ok := x.GetShow().(*StatusTest_Hh); ok {
		return x.Hh
	}
	return 0
}

type isStatusTest_Show interface {
	isStatusTest_Show()
}

type StatusTest_Test struct {
	Test string `protobuf:"bytes,2,opt,name=test,proto3,oneof"`
}

type StatusTest_Hh struct {
	Hh int32 `protobuf:"varint,3,opt,name=hh,proto3,oneof"`
}

func (*StatusTest_Test) isStatusTest_Show() {}

func (*StatusTest_Hh) isStatusTest_Show() {}

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bar int32       `protobuf:"varint,1,opt,name=bar,proto3" json:"bar,omitempty"`
	St  *StatusTest `protobuf:"bytes,2,opt,name=st,proto3" json:"st,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *Test) GetBar() int32 {
	if x != nil {
		return x.Bar
	}
	return 0
}

func (x *Test) GetSt() *StatusTest {
	if x != nil {
		return x.St
	}
	return nil
}

type NiuYa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo int32  `protobuf:"varint,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Oy  string `protobuf:"bytes,2,opt,name=oy,proto3" json:"oy,omitempty"`
}

func (x *NiuYa) Reset() {
	*x = NiuYa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NiuYa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NiuYa) ProtoMessage() {}

func (x *NiuYa) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NiuYa.ProtoReflect.Descriptor instead.
func (*NiuYa) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{2}
}

func (x *NiuYa) GetFoo() int32 {
	if x != nil {
		return x.Foo
	}
	return 0
}

func (x *NiuYa) GetOy() string {
	if x != nil {
		return x.Oy
	}
	return ""
}

var File_oneof_proto protoreflect.FileDescriptor

var file_oneof_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x22, 0x4c, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6a, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6a, 0x6b, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x02, 0x68, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x68, 0x68, 0x42, 0x06, 0x0a, 0x04, 0x73, 0x68,
	0x6f, 0x77, 0x22, 0x3b, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x62, 0x61, 0x72, 0x12, 0x21, 0x0a, 0x02,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x65, 0x73, 0x74, 0x52, 0x02, 0x73, 0x74, 0x22,
	0x29, 0x0a, 0x05, 0x4e, 0x69, 0x75, 0x59, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x66, 0x6f, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x74,
	0x75, 0x64, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneof_proto_rawDescOnce sync.Once
	file_oneof_proto_rawDescData = file_oneof_proto_rawDesc
)

func file_oneof_proto_rawDescGZIP() []byte {
	file_oneof_proto_rawDescOnce.Do(func() {
		file_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneof_proto_rawDescData)
	})
	return file_oneof_proto_rawDescData
}

var file_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_oneof_proto_goTypes = []interface{}{
	(*StatusTest)(nil), // 0: oneof.StatusTest
	(*Test)(nil),       // 1: oneof.Test
	(*NiuYa)(nil),      // 2: oneof.NiuYa
}
var file_oneof_proto_depIdxs = []int32{
	0, // 0: oneof.Test.st:type_name -> oneof.StatusTest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oneof_proto_init() }
func file_oneof_proto_init() {
	if File_oneof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NiuYa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oneof_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StatusTest_Test)(nil),
		(*StatusTest_Hh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneof_proto_goTypes,
		DependencyIndexes: file_oneof_proto_depIdxs,
		MessageInfos:      file_oneof_proto_msgTypes,
	}.Build()
	File_oneof_proto = out.File
	file_oneof_proto_rawDesc = nil
	file_oneof_proto_goTypes = nil
	file_oneof_proto_depIdxs = nil
}
